# -*- coding: utf-8 -*-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qLxCRmub8TCaeWwlpCELrbDkt7dFJeJl
"""

import gradio as gr
import random
import time

# -----------------------------
#  random list generator (returns only the CSV list string)
# -----------------------------
def generate_random_list():
    lst = sorted(random.sample(range(1, 100), 10))
    lst_str = ",".join(map(str, lst))
    # return only the CSV string so the list_box contains exactly numbers
    return lst_str

# -----------------------------
# binary search function
# -----------------------------
def binary_search(target, custom_list):
    # Ensure custom_list contains the CSV string of numbers and target is provided
    if target is None or (custom_list is None) or custom_list.strip() == "":
        return "❌ Please generate or enter a list AND enter a target value."

    try:
        # coerce target to int (gr.Number may come as float)
        target = int(target)
        # parse CSV list (allow spaces after commas)
        arr = [int(x.strip()) for x in custom_list.split(",") if x.strip() != ""]
        arr = sorted(arr)
    except Exception as e:
        return "❌ Invalid input. Use only numbers separated by commas."

    steps = []
    low, high = 0, len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        steps.append(f"Checking middle index {mid} → value {arr[mid]}")
        time.sleep(0.25)

        if arr[mid] == target:
            steps.append(f"✅ Target {target} FOUND at index {mid}")
            return "\n".join(steps)

        elif arr[mid] < target:
            steps.append("Target is greater → move RIGHT")
            low = mid + 1
        else:
            steps.append("Target is smaller → move LEFT")
            high = mid - 1

    steps.append(f"❌ Target {target} NOT FOUND")
    return "\n".join(steps)

# -----------------------------
# clean and simple UI (generate -> list_box, search uses list_box)
# -----------------------------
with gr.Blocks() as app:

    gr.Markdown("""
    # 🔍 Binary Search Algorithm Simulator
    This app demonstrates how Binary Search works step-by-step on a sorted list.
    """)

    with gr.Row():
        generate_btn = gr.Button("🎲 Generate Random Sorted List")
        list_box = gr.Textbox(label="Current List (CSV)", placeholder="Click generate or paste numbers like: 3,7,12,44")

    target_input = gr.Number(label="Enter Target Value")

    search_btn = gr.Button("🔍 Run Binary Search")

    output_box = gr.Textbox(label="Binary Search Steps", lines=10)

    # button connections — generate returns one value (the CSV list string)
    generate_btn.click(generate_random_list, outputs=[list_box])
    search_btn.click(binary_search, inputs=[target_input, list_box], outputs=output_box)

app.launch(debug=True)
